  options:
    logging: CLOUD_LOGGING_ONLY
    pool: {}
  projectId: unhide-inventory
  steps:
  - name: gcr.io/k8s-skaffold/pack
    entrypoint: pack
    args:
    - build
    - us-central1-docker.pkg.dev/unhide-inventory/Gcloud-Test/gcloud-test
    - --builder
    - gcr.io/buildpacks/builder:latest
    - --network
    - cloudbuild
  images:
  - us-central1-docker.pkg.dev/unhide-inventory/Gcloud-Test/gcloud-test